services:

  mysqldb:
    image: mysql:latest
    container_name: com.codedecode.db.container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=localhost
      - TZ=America/Chicago  # Match app timezone
    volumes:
      - com.codedecode.data:/var/lib/mysql
    networks:
      - com.codedecode.network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: com.codedecode.phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysqldb
      UPLOAD_LIMIT: 300M
    networks:
      - itr.trackingwebapp.network